/* soapStub.h
   Generated by gSOAP 2.8.17r from mcu.interface.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20817
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_mcu__Version
#define SOAP_TYPE_mcu__Version (7)
/* mcu:Version */
struct mcu__Version
{
public:
	int major;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	int minor;	/* required element of type xsd:int */
	char *desc;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 7; } /* = unique type id SOAP_TYPE_mcu__Version */
};
#endif

#ifndef SOAP_TYPE_mcu__getVersion
#define SOAP_TYPE_mcu__getVersion (13)
/* mcu:getVersion */
struct mcu__getVersion
{
public:
	void *_param_1;	/* transient */
public:
	int soap_type() const { return 13; } /* = unique type id SOAP_TYPE_mcu__getVersion */
};
#endif

#ifndef SOAP_TYPE_mcu__Status
#define SOAP_TYPE_mcu__Status (14)
/* mcu:Status */
struct mcu__Status
{
public:
	double uptime;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:double */
	int conferences;	/* required element of type xsd:int */
	double up_kbps5;	/* required element of type xsd:double */
	double up_kbps60;	/* required element of type xsd:double */
	double up_kbps300;	/* required element of type xsd:double */
	double down_kbps5;	/* required element of type xsd:double */
	double down_kbps60;	/* required element of type xsd:double */
	double down_kbps300;	/* required element of type xsd:double */
	double cpu;	/* required element of type xsd:double */
	double mem;	/* required element of type xsd:double */
	double up_lost_ratio;	/* required element of type xsd:double */
	double down_lost_ratio;	/* required element of type xsd:double */
public:
	int soap_type() const { return 14; } /* = unique type id SOAP_TYPE_mcu__Status */
};
#endif

#ifndef SOAP_TYPE_mcu__getStatus
#define SOAP_TYPE_mcu__getStatus (19)
/* mcu:getStatus */
struct mcu__getStatus
{
public:
	void *_param_2;	/* transient */
public:
	int soap_type() const { return 19; } /* = unique type id SOAP_TYPE_mcu__getStatus */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (20)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 20; } /* = unique type id SOAP_TYPE_SOAP_ENV__Header */
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (21)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 21; } /* = unique type id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (23)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 23; } /* = unique type id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (24)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 24; } /* = unique type id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (25)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 25; } /* = unique type id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_mcu__VersionResponse
#define SOAP_TYPE_mcu__VersionResponse (8)
typedef struct mcu__Version mcu__VersionResponse;
#endif

#ifndef SOAP_TYPE_mcu__StatusResponse
#define SOAP_TYPE_mcu__StatusResponse (16)
typedef struct mcu__Status mcu__StatusResponse;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 mcu__getVersion(struct soap*, void *_param_1, struct mcu__Version &ver);

SOAP_FMAC5 int SOAP_FMAC6 mcu__getStatus(struct soap*, void *_param_2, struct mcu__Status &res);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_mcu__getVersion(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_mcu__getStatus(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_mcu__getVersion(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_param_1, struct mcu__Version &ver);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_mcu__getStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_param_2, struct mcu__Status &res);

#endif

/* End of soapStub.h */
