//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.32559
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZQNB.Gateway.LiveService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Live", Namespace="http://schemas.datacontract.org/2004/07/ZQNB.Gateway.LiveService")]
    public partial class Live : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string GradeField;
        
        private System.Guid GuidField;
        
        private bool IsPublicField;
        
        private ZQNB.Gateway.LiveService.LiveUrl[] LiveUrlsField;
        
        private string OwnerField;
        
        private string SubjectField;
        
        private string TeacherField;
        
        private string TitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grade
        {
            get
            {
                return this.GradeField;
            }
            set
            {
                this.GradeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublic
        {
            get
            {
                return this.IsPublicField;
            }
            set
            {
                this.IsPublicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZQNB.Gateway.LiveService.LiveUrl[] LiveUrls
        {
            get
            {
                return this.LiveUrlsField;
            }
            set
            {
                this.LiveUrlsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Owner
        {
            get
            {
                return this.OwnerField;
            }
            set
            {
                this.OwnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Teacher
        {
            get
            {
                return this.TeacherField;
            }
            set
            {
                this.TeacherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LiveUrl", Namespace="http://schemas.datacontract.org/2004/07/ZQNB.Gateway.LiveService")]
    public partial class LiveUrl : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TagField;
        
        private string UrlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/ZQNB.Gateway.LiveService")]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private bool SuccessField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ILiveCourseNotify")]
public interface ILiveCourseNotify
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiveCourseNotify/NotifyRecordingStart", ReplyAction="http://tempuri.org/ILiveCourseNotify/NotifyRecordingStartResponse")]
    ZQNB.Gateway.LiveService.OperationResult NotifyRecordingStart(ZQNB.Gateway.LiveService.Live liveCourse, string machineId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiveCourseNotify/HeartBeat", ReplyAction="http://tempuri.org/ILiveCourseNotify/HeartBeatResponse")]
    ZQNB.Gateway.LiveService.OperationResult HeartBeat(string machineId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiveCourseNotify/NotifyRecordingStop", ReplyAction="http://tempuri.org/ILiveCourseNotify/NotifyRecordingStopResponse")]
    ZQNB.Gateway.LiveService.OperationResult NotifyRecordingStop(string machineId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILiveCourseNotifyChannel : ILiveCourseNotify, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LiveCourseNotifyClient : System.ServiceModel.ClientBase<ILiveCourseNotify>, ILiveCourseNotify
{
    
    public LiveCourseNotifyClient()
    {
    }
    
    public LiveCourseNotifyClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LiveCourseNotifyClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LiveCourseNotifyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LiveCourseNotifyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ZQNB.Gateway.LiveService.OperationResult NotifyRecordingStart(ZQNB.Gateway.LiveService.Live liveCourse, string machineId)
    {
        return base.Channel.NotifyRecordingStart(liveCourse, machineId);
    }
    
    public ZQNB.Gateway.LiveService.OperationResult HeartBeat(string machineId)
    {
        return base.Channel.HeartBeat(machineId);
    }
    
    public ZQNB.Gateway.LiveService.OperationResult NotifyRecordingStop(string machineId)
    {
        return base.Channel.NotifyRecordingStop(machineId);
    }
}
