/* soapStub.h
   Generated by gSOAP 2.8.17r from zonekey.mcu.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20817
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_zkmcu__getVersionResponse
#define SOAP_TYPE_zkmcu__getVersionResponse (11)
/* zkmcu:getVersionResponse */
struct zkmcu__getVersionResponse
{
public:
	char **info;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
public:
	int soap_type() const { return 11; } /* = unique type id SOAP_TYPE_zkmcu__getVersionResponse */
};
#endif

#ifndef SOAP_TYPE_zkmcu__getVersion
#define SOAP_TYPE_zkmcu__getVersion (12)
/* zkmcu:getVersion */
struct zkmcu__getVersion
{
public:
	void *_param_1;	/* transient */
public:
	int soap_type() const { return 12; } /* = unique type id SOAP_TYPE_zkmcu__getVersion */
};
#endif

#ifndef SOAP_TYPE_zkmcu__SysInfo
#define SOAP_TYPE_zkmcu__SysInfo (13)
/* zkmcu:SysInfo */
struct zkmcu__SysInfo
{
public:
	double cpu;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:double */
	double mem;	/* required element of type xsd:double */
	double net_USCOREsent;	/* required element of type xsd:double */
	double net_USCORErecv;	/* required element of type xsd:double */
public:
	int soap_type() const { return 13; } /* = unique type id SOAP_TYPE_zkmcu__SysInfo */
};
#endif

#ifndef SOAP_TYPE_zkmcu__getSysInfo
#define SOAP_TYPE_zkmcu__getSysInfo (18)
/* zkmcu:getSysInfo */
struct zkmcu__getSysInfo
{
public:
	void *_param_2;	/* transient */
public:
	int soap_type() const { return 18; } /* = unique type id SOAP_TYPE_zkmcu__getSysInfo */
};
#endif

#ifndef SOAP_TYPE_zkmcu__CreateConference
#define SOAP_TYPE_zkmcu__CreateConference (19)
/* zkmcu:CreateConference */
struct zkmcu__CreateConference
{
public:
	int mode;	/* required element of type xsd:int */
	int livingcast;	/* required element of type xsd:int */
	char *desc;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 19; } /* = unique type id SOAP_TYPE_zkmcu__CreateConference */
};
#endif

#ifndef SOAP_TYPE_zkmcu__CreateConferenceResponse
#define SOAP_TYPE_zkmcu__CreateConferenceResponse (20)
/* zkmcu:CreateConferenceResponse */
struct zkmcu__CreateConferenceResponse
{
public:
	int cid;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	char *reason;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 20; } /* = unique type id SOAP_TYPE_zkmcu__CreateConferenceResponse */
};
#endif

#ifndef SOAP_TYPE_zkmcu__createConference
#define SOAP_TYPE_zkmcu__createConference (24)
/* zkmcu:createConference */
struct zkmcu__createConference
{
public:
	struct zkmcu__CreateConference *req;	/* optional element of type zkmcu:CreateConference */
public:
	int soap_type() const { return 24; } /* = unique type id SOAP_TYPE_zkmcu__createConference */
};
#endif

#ifndef SOAP_TYPE_zkmcu__destroyConference
#define SOAP_TYPE_zkmcu__destroyConference (26)
/* zkmcu:destroyConference */
struct zkmcu__destroyConference
{
public:
	int cid;	/* required element of type xsd:int */
public:
	int soap_type() const { return 26; } /* = unique type id SOAP_TYPE_zkmcu__destroyConference */
};
#endif

#ifndef SOAP_TYPE_zkmcu__ConferenceIdArray
#define SOAP_TYPE_zkmcu__ConferenceIdArray (27)
/* Sequence of zkmcu:ConferenceIdArray schema type: */
struct zkmcu__ConferenceIdArray
{
public:
	int *__ptr;
	int __size;
public:
	int soap_type() const { return 27; } /* = unique type id SOAP_TYPE_zkmcu__ConferenceIdArray */
};
#endif

#ifndef SOAP_TYPE_zkmcu__listConferencesResponse
#define SOAP_TYPE_zkmcu__listConferencesResponse (32)
/* zkmcu:listConferencesResponse */
struct zkmcu__listConferencesResponse
{
public:
	struct zkmcu__ConferenceIdArray res;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type zkmcu:ConferenceIdArrayResponse */
public:
	int soap_type() const { return 32; } /* = unique type id SOAP_TYPE_zkmcu__listConferencesResponse */
};
#endif

#ifndef SOAP_TYPE_zkmcu__listConferences
#define SOAP_TYPE_zkmcu__listConferences (33)
/* zkmcu:listConferences */
struct zkmcu__listConferences
{
public:
	void *_param_4;	/* transient */
public:
	int soap_type() const { return 33; } /* = unique type id SOAP_TYPE_zkmcu__listConferences */
};
#endif

#ifndef SOAP_TYPE_zkmcu__StreamInfo
#define SOAP_TYPE_zkmcu__StreamInfo (34)
/* zkmcu:StreamInfo */
struct zkmcu__StreamInfo
{
public:
	int streamid;	/* required element of type xsd:int */
	char *desc;	/* optional element of type xsd:string */
	long sent;	/* required element of type xsd:long */
	long recv;	/* required element of type xsd:long */
	long lost_USCOREsent;	/* required element of type xsd:long */
	long lost_USCORErecv;	/* required element of type xsd:long */
	int jitter;	/* required element of type xsd:int */
public:
	int soap_type() const { return 34; } /* = unique type id SOAP_TYPE_zkmcu__StreamInfo */
};
#endif

#ifndef SOAP_TYPE_zkmcu__StreamInfoArray
#define SOAP_TYPE_zkmcu__StreamInfoArray (36)
/* Sequence of zkmcu:StreamInfoArray schema type: */
struct zkmcu__StreamInfoArray
{
public:
	struct zkmcu__StreamInfo *__ptr;
	int __size;
public:
	int soap_type() const { return 36; } /* = unique type id SOAP_TYPE_zkmcu__StreamInfoArray */
};
#endif

#ifndef SOAP_TYPE_zkmcu__SourceInfo
#define SOAP_TYPE_zkmcu__SourceInfo (38)
/* zkmcu:SourceInfo */
struct zkmcu__SourceInfo
{
public:
	int sourceid;	/* required element of type xsd:int */
	char *desc;	/* optional element of type xsd:string */
	long lost;	/* required element of type xsd:long */
	long recv;	/* required element of type xsd:long */
public:
	int soap_type() const { return 38; } /* = unique type id SOAP_TYPE_zkmcu__SourceInfo */
};
#endif

#ifndef SOAP_TYPE_zkmcu__SourceInfoArray
#define SOAP_TYPE_zkmcu__SourceInfoArray (39)
/* Sequence of zkmcu:SourceInfoArray schema type: */
struct zkmcu__SourceInfoArray
{
public:
	struct zkmcu__SourceInfo *__ptr;
	int __size;
public:
	int soap_type() const { return 39; } /* = unique type id SOAP_TYPE_zkmcu__SourceInfoArray */
};
#endif

#ifndef SOAP_TYPE_zkmcu__SinkInfo
#define SOAP_TYPE_zkmcu__SinkInfo (41)
/* zkmcu:SinkInfo */
struct zkmcu__SinkInfo
{
public:
	int sinkid;	/* required element of type xsd:int */
	char *desc;	/* optional element of type xsd:string */
	long sent;	/* required element of type xsd:long */
	long lost;	/* required element of type xsd:long */
	int jitter;	/* required element of type xsd:int */
public:
	int soap_type() const { return 41; } /* = unique type id SOAP_TYPE_zkmcu__SinkInfo */
};
#endif

#ifndef SOAP_TYPE_zkmcu__SinkInfoArray
#define SOAP_TYPE_zkmcu__SinkInfoArray (42)
/* Sequence of zkmcu:SinkInfoArray schema type: */
struct zkmcu__SinkInfoArray
{
public:
	struct zkmcu__SinkInfo *__ptr;
	int __size;
public:
	int soap_type() const { return 42; } /* = unique type id SOAP_TYPE_zkmcu__SinkInfoArray */
};
#endif

#ifndef SOAP_TYPE_zkmcu__ConferenceInfo
#define SOAP_TYPE_zkmcu__ConferenceInfo (44)
/* zkmcu:ConferenceInfo */
struct zkmcu__ConferenceInfo
{
public:
	int cid;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	int mode;	/* required element of type xsd:int */
	double uptime;	/* required element of type xsd:double */
	char *desc;	/* optional element of type xsd:string */
	struct zkmcu__StreamInfoArray *streams;	/* optional element of type zkmcu:StreamInfoArray */
	struct zkmcu__SourceInfoArray *sources;	/* optional element of type zkmcu:SourceInfoArray */
	struct zkmcu__SinkInfoArray *sinks;	/* optional element of type zkmcu:SinkInfoArray */
public:
	int soap_type() const { return 44; } /* = unique type id SOAP_TYPE_zkmcu__ConferenceInfo */
};
#endif

#ifndef SOAP_TYPE_zkmcu__infoConference
#define SOAP_TYPE_zkmcu__infoConference (51)
/* zkmcu:infoConference */
struct zkmcu__infoConference
{
public:
	int cid;	/* required element of type xsd:int */
public:
	int soap_type() const { return 51; } /* = unique type id SOAP_TYPE_zkmcu__infoConference */
};
#endif

#ifndef SOAP_TYPE_zkmcu__MediaEndPoint
#define SOAP_TYPE_zkmcu__MediaEndPoint (52)
/* zkmcu:MediaEndPoint */
struct zkmcu__MediaEndPoint
{
public:
	int rtp_USCOREport;	/* required element of type xsd:int */
	int rtcp_USCOREport;	/* required element of type xsd:int */
	char *server_USCOREip;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 52; } /* = unique type id SOAP_TYPE_zkmcu__MediaEndPoint */
};
#endif

#ifndef SOAP_TYPE_zkmcu__AddSourceRequest
#define SOAP_TYPE_zkmcu__AddSourceRequest (53)
/* zkmcu:AddSourceRequest */
struct zkmcu__AddSourceRequest
{
public:
	int payload;	/* required element of type xsd:int */
	char *desc;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 53; } /* = unique type id SOAP_TYPE_zkmcu__AddSourceRequest */
};
#endif

#ifndef SOAP_TYPE_zkmcu__AddSourceResponse
#define SOAP_TYPE_zkmcu__AddSourceResponse (54)
/* zkmcu:AddSourceResponse */
struct zkmcu__AddSourceResponse
{
public:
	int sourceid;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	char *reason;	/* optional element of type xsd:string */
	struct zkmcu__MediaEndPoint media;	/* required element of type zkmcu:MediaEndPoint */
public:
	int soap_type() const { return 54; } /* = unique type id SOAP_TYPE_zkmcu__AddSourceResponse */
};
#endif

#ifndef SOAP_TYPE_zkmcu__addSource
#define SOAP_TYPE_zkmcu__addSource (58)
/* zkmcu:addSource */
struct zkmcu__addSource
{
public:
	int cid;	/* required element of type xsd:int */
	struct zkmcu__AddSourceRequest *req;	/* optional element of type zkmcu:AddSourceRequest */
public:
	int soap_type() const { return 58; } /* = unique type id SOAP_TYPE_zkmcu__addSource */
};
#endif

#ifndef SOAP_TYPE_zkmcu__delSource
#define SOAP_TYPE_zkmcu__delSource (60)
/* zkmcu:delSource */
struct zkmcu__delSource
{
public:
	int cid;	/* required element of type xsd:int */
	int sourceid;	/* required element of type xsd:int */
public:
	int soap_type() const { return 60; } /* = unique type id SOAP_TYPE_zkmcu__delSource */
};
#endif

#ifndef SOAP_TYPE_zkmcu__AddSinkRequest
#define SOAP_TYPE_zkmcu__AddSinkRequest (61)
/* zkmcu:AddSinkRequest */
struct zkmcu__AddSinkRequest
{
public:
	int payload;	/* required element of type xsd:int */
	char *desc;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 61; } /* = unique type id SOAP_TYPE_zkmcu__AddSinkRequest */
};
#endif

#ifndef SOAP_TYPE_zkmcu__AddSinkResponse
#define SOAP_TYPE_zkmcu__AddSinkResponse (62)
/* zkmcu:AddSinkResponse */
struct zkmcu__AddSinkResponse
{
public:
	int sinkid;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	char *reason;	/* optional element of type xsd:string */
	struct zkmcu__MediaEndPoint media;	/* required element of type zkmcu:MediaEndPoint */
public:
	int soap_type() const { return 62; } /* = unique type id SOAP_TYPE_zkmcu__AddSinkResponse */
};
#endif

#ifndef SOAP_TYPE_zkmcu__addSink
#define SOAP_TYPE_zkmcu__addSink (66)
/* zkmcu:addSink */
struct zkmcu__addSink
{
public:
	int cid;	/* required element of type xsd:int */
	struct zkmcu__AddSinkRequest *req;	/* optional element of type zkmcu:AddSinkRequest */
public:
	int soap_type() const { return 66; } /* = unique type id SOAP_TYPE_zkmcu__addSink */
};
#endif

#ifndef SOAP_TYPE_zkmcu__delSink
#define SOAP_TYPE_zkmcu__delSink (68)
/* zkmcu:delSink */
struct zkmcu__delSink
{
public:
	int cid;	/* required element of type xsd:int */
	int sinkid;	/* required element of type xsd:int */
public:
	int soap_type() const { return 68; } /* = unique type id SOAP_TYPE_zkmcu__delSink */
};
#endif

#ifndef SOAP_TYPE_zkmcu__AddStreamRequest
#define SOAP_TYPE_zkmcu__AddStreamRequest (69)
/* zkmcu:AddStreamRequest */
struct zkmcu__AddStreamRequest
{
public:
	int payload;	/* required element of type xsd:int */
	char *desc;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 69; } /* = unique type id SOAP_TYPE_zkmcu__AddStreamRequest */
};
#endif

#ifndef SOAP_TYPE_zkmcu__AddStreamResponse
#define SOAP_TYPE_zkmcu__AddStreamResponse (70)
/* zkmcu:AddStreamResponse */
struct zkmcu__AddStreamResponse
{
public:
	int streamid;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	char *reason;	/* optional element of type xsd:string */
	struct zkmcu__MediaEndPoint media;	/* required element of type zkmcu:MediaEndPoint */
public:
	int soap_type() const { return 70; } /* = unique type id SOAP_TYPE_zkmcu__AddStreamResponse */
};
#endif

#ifndef SOAP_TYPE_zkmcu__addStream
#define SOAP_TYPE_zkmcu__addStream (74)
/* zkmcu:addStream */
struct zkmcu__addStream
{
public:
	int cid;	/* required element of type xsd:int */
	struct zkmcu__AddStreamRequest *req;	/* optional element of type zkmcu:AddStreamRequest */
public:
	int soap_type() const { return 74; } /* = unique type id SOAP_TYPE_zkmcu__addStream */
};
#endif

#ifndef SOAP_TYPE_zkmcu__delStream
#define SOAP_TYPE_zkmcu__delStream (76)
/* zkmcu:delStream */
struct zkmcu__delStream
{
public:
	int cid;	/* required element of type xsd:int */
	int sourceid;	/* required element of type xsd:int */
public:
	int soap_type() const { return 76; } /* = unique type id SOAP_TYPE_zkmcu__delStream */
};
#endif

#ifndef SOAP_TYPE_zkmcu__KeyValue
#define SOAP_TYPE_zkmcu__KeyValue (77)
/* zkmcu:KeyValue */
struct zkmcu__KeyValue
{
public:
	char *key;	/* optional element of type xsd:string */
	char *value;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 77; } /* = unique type id SOAP_TYPE_zkmcu__KeyValue */
};
#endif

#ifndef SOAP_TYPE_zkmcu__KeyValueArray
#define SOAP_TYPE_zkmcu__KeyValueArray (78)
/* Sequence of zkmcu:KeyValueArray schema type: */
struct zkmcu__KeyValueArray
{
public:
	struct zkmcu__KeyValue *__ptr;
	int __size;
public:
	int soap_type() const { return 78; } /* = unique type id SOAP_TYPE_zkmcu__KeyValueArray */
};
#endif

#ifndef SOAP_TYPE_zkmcu__setParams
#define SOAP_TYPE_zkmcu__setParams (83)
/* zkmcu:setParams */
struct zkmcu__setParams
{
public:
	int cid;	/* required element of type xsd:int */
	struct zkmcu__KeyValueArray *req;	/* optional element of type zkmcu:KeyValueArray */
public:
	int soap_type() const { return 83; } /* = unique type id SOAP_TYPE_zkmcu__setParams */
};
#endif

#ifndef SOAP_TYPE_zkmcu__getParamsResponse
#define SOAP_TYPE_zkmcu__getParamsResponse (86)
/* zkmcu:getParamsResponse */
struct zkmcu__getParamsResponse
{
public:
	struct zkmcu__KeyValueArray res;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type zkmcu:KeyValueArrayResponse */
public:
	int soap_type() const { return 86; } /* = unique type id SOAP_TYPE_zkmcu__getParamsResponse */
};
#endif

#ifndef SOAP_TYPE_zkmcu__getParams
#define SOAP_TYPE_zkmcu__getParams (87)
/* zkmcu:getParams */
struct zkmcu__getParams
{
public:
	int cid;	/* required element of type xsd:int */
public:
	int soap_type() const { return 87; } /* = unique type id SOAP_TYPE_zkmcu__getParams */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (88)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 88; } /* = unique type id SOAP_TYPE_SOAP_ENV__Header */
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (89)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 89; } /* = unique type id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (91)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 91; } /* = unique type id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (92)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 92; } /* = unique type id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (93)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 93; } /* = unique type id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_zkmcu__SysInfoResponse
#define SOAP_TYPE_zkmcu__SysInfoResponse (15)
typedef struct zkmcu__SysInfo zkmcu__SysInfoResponse;
#endif

#ifndef SOAP_TYPE_zkmcu__ConferenceIdArrayResponse
#define SOAP_TYPE_zkmcu__ConferenceIdArrayResponse (29)
typedef struct zkmcu__ConferenceIdArray zkmcu__ConferenceIdArrayResponse;
#endif

#ifndef SOAP_TYPE_zkmcu__ConferenceInfoResponse
#define SOAP_TYPE_zkmcu__ConferenceInfoResponse (48)
typedef struct zkmcu__ConferenceInfo zkmcu__ConferenceInfoResponse;
#endif

#ifndef SOAP_TYPE_zkmcu__KeyValueArrayResponse
#define SOAP_TYPE_zkmcu__KeyValueArrayResponse (80)
typedef struct zkmcu__KeyValueArray zkmcu__KeyValueArrayResponse;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 zkmcu__getVersion(struct soap*, void *_param_1, char **info);

SOAP_FMAC5 int SOAP_FMAC6 zkmcu__getSysInfo(struct soap*, void *_param_2, struct zkmcu__SysInfo &res);

SOAP_FMAC5 int SOAP_FMAC6 zkmcu__createConference(struct soap*, struct zkmcu__CreateConference *req, struct zkmcu__CreateConferenceResponse &res);

SOAP_FMAC5 int SOAP_FMAC6 zkmcu__destroyConference(struct soap*, int cid);

SOAP_FMAC5 int SOAP_FMAC6 zkmcu__listConferences(struct soap*, void *_param_4, struct zkmcu__ConferenceIdArray &res);

SOAP_FMAC5 int SOAP_FMAC6 zkmcu__infoConference(struct soap*, int cid, struct zkmcu__ConferenceInfo &res);

SOAP_FMAC5 int SOAP_FMAC6 zkmcu__addSource(struct soap*, int cid, struct zkmcu__AddSourceRequest *req, struct zkmcu__AddSourceResponse &res);

SOAP_FMAC5 int SOAP_FMAC6 zkmcu__delSource(struct soap*, int cid, int sourceid);

SOAP_FMAC5 int SOAP_FMAC6 zkmcu__addSink(struct soap*, int cid, struct zkmcu__AddSinkRequest *req, struct zkmcu__AddSinkResponse &res);

SOAP_FMAC5 int SOAP_FMAC6 zkmcu__delSink(struct soap*, int cid, int sinkid);

SOAP_FMAC5 int SOAP_FMAC6 zkmcu__addStream(struct soap*, int cid, struct zkmcu__AddStreamRequest *req, struct zkmcu__AddStreamResponse &res);

SOAP_FMAC5 int SOAP_FMAC6 zkmcu__delStream(struct soap*, int cid, int sourceid);

SOAP_FMAC5 int SOAP_FMAC6 zkmcu__setParams(struct soap*, int cid, struct zkmcu__KeyValueArray *req);

SOAP_FMAC5 int SOAP_FMAC6 zkmcu__getParams(struct soap*, int cid, struct zkmcu__KeyValueArray &res);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkmcu__getVersion(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkmcu__getSysInfo(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkmcu__createConference(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkmcu__destroyConference(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkmcu__listConferences(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkmcu__infoConference(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkmcu__addSource(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkmcu__delSource(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkmcu__addSink(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkmcu__delSink(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkmcu__addStream(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkmcu__delStream(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkmcu__setParams(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkmcu__getParams(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkmcu__getVersion(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_param_1, char **info);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkmcu__getSysInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_param_2, struct zkmcu__SysInfo &res);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkmcu__createConference(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct zkmcu__CreateConference *req, struct zkmcu__CreateConferenceResponse &res);

SOAP_FMAC5 int SOAP_FMAC6 soap_send_zkmcu__destroyConference(struct soap *soap, const char *soap_endpoint, const char *soap_action, int cid);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_zkmcu__destroyConference(struct soap *soap, struct zkmcu__destroyConference *_param_3);


SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkmcu__listConferences(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_param_4, struct zkmcu__ConferenceIdArray &res);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkmcu__infoConference(struct soap *soap, const char *soap_endpoint, const char *soap_action, int cid, struct zkmcu__ConferenceInfo &res);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkmcu__addSource(struct soap *soap, const char *soap_endpoint, const char *soap_action, int cid, struct zkmcu__AddSourceRequest *req, struct zkmcu__AddSourceResponse &res);

SOAP_FMAC5 int SOAP_FMAC6 soap_send_zkmcu__delSource(struct soap *soap, const char *soap_endpoint, const char *soap_action, int cid, int sourceid);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_zkmcu__delSource(struct soap *soap, struct zkmcu__delSource *_param_5);


SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkmcu__addSink(struct soap *soap, const char *soap_endpoint, const char *soap_action, int cid, struct zkmcu__AddSinkRequest *req, struct zkmcu__AddSinkResponse &res);

SOAP_FMAC5 int SOAP_FMAC6 soap_send_zkmcu__delSink(struct soap *soap, const char *soap_endpoint, const char *soap_action, int cid, int sinkid);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_zkmcu__delSink(struct soap *soap, struct zkmcu__delSink *_param_6);


SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkmcu__addStream(struct soap *soap, const char *soap_endpoint, const char *soap_action, int cid, struct zkmcu__AddStreamRequest *req, struct zkmcu__AddStreamResponse &res);

SOAP_FMAC5 int SOAP_FMAC6 soap_send_zkmcu__delStream(struct soap *soap, const char *soap_endpoint, const char *soap_action, int cid, int sourceid);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_zkmcu__delStream(struct soap *soap, struct zkmcu__delStream *_param_7);


SOAP_FMAC5 int SOAP_FMAC6 soap_send_zkmcu__setParams(struct soap *soap, const char *soap_endpoint, const char *soap_action, int cid, struct zkmcu__KeyValueArray *req);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_zkmcu__setParams(struct soap *soap, struct zkmcu__setParams *_param_8);


SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkmcu__getParams(struct soap *soap, const char *soap_endpoint, const char *soap_action, int cid, struct zkmcu__KeyValueArray &res);

#endif

/* End of soapStub.h */
